WebTracker/Controllers/AdminLteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebTracker.Models;
using WebTracker.Repositories;
using Newtonsoft.Json;
namespace WebTracker.Controllers
{
    public class AdminLteController : Controller
    {
        private readonly ILogger<AdminLteController> _logger;
        private readonly IWebsiteRepository _websiteRepository;
        private readonly IUserRepository _userRepository;
        private readonly IFlowRepository _flowRepository;
        private readonly IUrlRepository _urlRepository;
        private readonly IActionRepository _actionRepository;
        private readonly IActionDataRepository _actionDataRepository;

        public AdminLteController(ILogger<AdminLteController> logger, IWebsiteRepository websiteRepository, IUserRepository userRepository, IFlowRepository flowRepository, IUrlRepository urlRepository, IActionRepository actionRepository, IActionDataRepository actionDataRepository)
        {
            _logger = logger;
            _websiteRepository = websiteRepository;
            _userRepository = userRepository;
            _flowRepository = flowRepository;
            _urlRepository = urlRepository;
            _actionRepository = actionRepository;
            _actionDataRepository = actionDataRepository;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Website> websites = await _websiteRepository.GetAllWebsites();
            for(int i = 0; i < websites.Count(); i++)
            {
                websites.ElementAt(i).Users = await _userRepository.GetUsersByWebsiteId(websites.ElementAt(i).WebsiteId);
            }
            return View(websites);
        }
        public async Task<IActionResult> WebsiteDetails(int id)
        {
            Website website = await _websiteRepository.GetWebsiteById(id);
            website.Users = await _userRepository.GetUsersByWebsiteId(website.WebsiteId);
            List <Tuple<string?, int>> urls = new List<Tuple<string?, int>>();
            foreach(User user in website.Users)
            {
                user.Flows = await _flowRepository.GetFlowsByUserId(user.UserId);
                urls.Add(Tuple.Create(Convert.ToString(user.Flows), 0));
                foreach(Flow flow in user.Flows)
                {
                    flow.Urls = await _urlRepository.GetUrlsByFlowId(flow.FlowId);
                }
            }
            for(int i = 0; i < urls.Count(); i++)
            {
                for(int j = i + 1; j <urls.Count(); j++ )
                {
                    if(urls[i].Item1 == urls[j].Item1)
                    {
                        urls[i] = Tuple.Create(urls[i].Item1, urls[i].Item2 + 1);
                        urls.RemoveAt(j);
                        j--;
                    }
                }
            }
            Console.WriteLine(urls);
            return View(website);
        }
        
        public async Task<IActionResult> UrlDetails(int id)
        {
            Url url = await _urlRepository.GetUrlById(id);
            url.Actions = await _actionRepository.GetActionsByUrlId(url.UrlId);
            foreach (Models.Action action in url.Actions)
            {
                action.Data = await _actionDataRepository.GetActionDataByActionId(action.ActionId);
            }

            return View(url);
        }
        public async Task<IActionResult> UniqueFlows(int id)
        {
            Flow flow = await _flowRepository.GetFlowById(id);

            return View(flow);
        }
        [HttpGet]
        public async Task<JsonResult> GetWebsiteById(int id)
        {
            Website website = await _websiteRepository.GetWebsiteById(id);
            foreach(var user in website.Users)
            {
                user.Website = null;
                foreach(var flow in user.Flows)
                {
                    flow.User = null;
                    foreach(var url in flow.Urls)
                    {
                        url.Flow = null;
                        foreach(var action in url.Actions)
                        {
                            action.Url = null;
                            action.Data = await _actionDataRepository.GetActionDataByActionId(action.ActionId);
                            foreach(var data in action.Data)
                            {
                                data.Action = null;
                            }
                        }
                    }
                }
            }
            return Json(website);
        }
        [HttpGet]
        public async Task<string> GetWebsiteByName(string name)
        {
            int websiteId = await _websiteRepository.GetWebsiteIdByName(name);
            Website website = await _websiteRepository.GetWebsiteById(websiteId);
            foreach(var user in website.Users)
            {
                user.Website = null;
                foreach(var flow in user.Flows)
                {
                    flow.User = null;
                    foreach(var url in flow.Urls)
                    {
                        url.Flow = null;
                        foreach(var action in url.Actions)
                        {
                            action.Url = null;
                            action.Data = await _actionDataRepository.GetActionDataByActionId(action.ActionId);
                            foreach(var data in action.Data)
                            {
                                data.Action = null;
                            }
                        }
                    }
                }
            }
            string result = JsonConvert.SerializeObject(website);
            return result;
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebTracker/Views/AdminLte/Index.cshtml
@model IEnumerable<Website>
@{
    ViewData["Title"] = "Websites";
}

    
<!-- All Websites -->
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Websites Being Tracked</h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        <table id="websitesDetails" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Web Urls</th>
            <th>Vistors Count</th>
            <th>Visit Count</th>
          </tr>
          </thead>
          <tbody>
          @foreach (var website in Model){
            <tr>
              <td>
                <a asp-controller="AdminLte" asp-action="WebsiteDetails" asp-route-id=@website.WebsiteId>
                  @website.Web
                </a>
              </td>
              <td>
                @website.Users.Count()
              </td>
              <td>
                @website.VisitCount
              </td>
            </tr>
          }
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
  </div>
</div>
<!-- /.row -->


<!-- page script -->
@section scripts {
  <script>
    $(function () {
      $('#websitesDetails').dataTable({
        "paging": true,
        "lengthChange": false,
        "searching": true,
        "ordering": false,
        "info": true,
        "autoWidth": true,
        "responsive": true,
      });
    });
  </script>

}

WebTracker/Views/AdminLte/UrlDetails.cshtml
@model WebTracker.Models.Url
@{
    ViewData["Title"] = "Url Details";
}


<!-- Url Details-->
<div class="row">
<div class="col-12">
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">Actions Performed On Url</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="urlDetails" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Type</th>
                <th>Content</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var action in Model.Actions){
                <tr>
                    <td>@action.Type</td>
                    <td>@action.Content</td>
                </tr>
                @if(action.Type != "Page Load"){
                    @foreach (var data in action.Data){
                        <tr>
                            <td>@data.Name</td>
                            <td>@data.Data</td>
                        </tr>
                    }
                }
            }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    </div>
</div>
</div>
<!-- /.row -->

@section scripts {
    <script>
        $(function () {
            {($('#urlDetails')).DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": false,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
            }
        });
    </script>
}
              

WebTracker/Views/AdminLte/WebsiteDetails.cshtml
a@model WebTracker.Models.Website
@{
    ViewData["Title"] = "Website Details";
}


<!-- Main content -->

<div class="row">
    <div class="col-md-6">
        <!-- DONUT CHART -->
        <div class="card card-danger">
            <div class="card-header">
            <h3 class="card-title">Visited From Browsers</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                </button>
            </div>
            </div>
            <div class="card-body">
            <canvas id="donutChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <div class="col-md-6">
        <!-- PIE CHART -->
        <div class="card card-danger">
            <div class="card-header">
            <h3 class="card-title">Visited From Devices</h3>

            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                </button>
            </div>
            </div>
            <div class="card-body">
            <canvas id="pieChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%;"></canvas>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>



<!-- Website Details-->
<div class="row">
<div class="col-12">
    <div class="card">
    <div class="card-header">
        <h3 class="card-title">Websites Being Tracked</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="websitesDetails" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Sr.</th>
                <th>Flows</th>
            </tr>
            </thead>
            <tbody>
                @{
                    int sr = 1;
                }
            @foreach (var user in Model.Users){
                @foreach (var flow in user.Flows)
                {
                    <tr>
                        <td>
                            <a asp-controller = "AdminLte" asp-action = "FlowDetails" asp-route-id = "@flow.FlowId">@sr</a>
                            @{sr++;}
                        </td>
                        <td>
                            @foreach (var url in flow.Urls)
                            {
                                <a asp-controller = "AdminLte" asp-action = "UrlDetails" asp-route-id = "@url.UrlId">@url.WebUrl</a>
                            }
                        </td>
                        @* <td>
                            <button asp-controller = "AdminLte" asp-action = "FlowDetails" asp-route-id = "@flow.FlowId">
                                Flow Details
                            </button>
                        </td> *@
                        
                    </tr>   
                }
            }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
    </div>
</div>
</div>
<!-- /.row -->

@section scripts {
    <script>
        $(function () {

        /* ChartJS
        * -------
        * Here we will create a few charts using ChartJS
        */
        let websiteName = '@Model.Web';
        @* await $.ajax({
            type: "GET",
            async: false,
            url: "@Url.Action("GetWebsiteByName", "AdminLte")",
            DataType: "text",
            data: {name: websiteName},
            success: function(result){
            website = JSON.parse(result);
            },
            error: function(req, status, error){
            console.log(req, status, error);
            }
        }).then(response => console.log("response: " + response)).catch(error => console.log("error: " + error)); *@
        //console.log("website", website);



        // get browser data
        var browsers = [0, 0, 0, 0, 0, 0];
        @foreach (var user in Model.Users){

            @if(user.Browser == "chrome"){
                @:browsers[0]++;
            }
            else if(user.Browser == "edge"){
                @:browsers[1]++;
            }
            else if(user.Browser == "firefox"){
                @:browsers[2]++;
            }
            else if(user.Browser == "safari"){
                @:browsers[3]++;
            }
            else if(user.Browser == "opera"){
                @:browsers[4]++;
            }
            else if(user.Browser == "No browser detection"){
                @:browsers[5]++;
            }
        }

        
        let devices = [0, 0, 0, 0];
        @foreach (var user in Model.Users){ 
            
            @if(user.DeviceType == "desktop") {
            @:devices[0]++;
            } else if (user.DeviceType == "mobile") {
            @:devices[1]++;
            } else if (user.DeviceType == "tablet") {
            @:devices[2]++;
            } else {
            @:devices[3]++;
            }
        }

        //-------------
        //- DONUT CHART -
        //-------------
        // Get context with jQuery - using jQuery's .get() method.
        var donutChartCanvas = $('#donutChart').get(0).getContext('2d')
        var donutData        = {
            labels: [
                'Chrome', 
                'Microsoft Edge',
                'FireFox', 
                'Safari', 
                'Opera', 
                'Other', 
            ],
            datasets: [
            {
                data: browsers,
                backgroundColor : ['#f56954', '#00a65a', '#f39c12', '#00c0ef', '#3c8dbc', '#d2d6de'],
            }
            ]
        }
        var donutOptions     = {
            maintainAspectRatio : false,
            responsive : true,
        }
        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        var donutChart = new Chart(donutChartCanvas, {
            type: 'doughnut',
            data: donutData,
            options: donutOptions      
        })

        //-------------
        //- PIE CHART -
        //-------------
        // Get context with jQuery - using jQuery's .get() method.
        var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
        var pieData        = {
            labels: [
                'Desktop', 
                'Mobile',
                'Tablet',
                'Other',
            ],
            datasets: [
            {
                data: devices,
                backgroundColor : ['#00c0ef', '#f56954', '#00a65a', '#d2d6de'],
            }
            ]
        }
        var pieOptions     = {
            maintainAspectRatio : false,
            responsive : true,
        }
        //Create pie or douhnut chart
        // You can switch between pie and douhnut using the method below.
        var pieChart = new Chart(pieChartCanvas, {
            type: 'pie',
            data: pieData,
            options: pieOptions      
        });
        {($('#websitesDetails')).DataTable({
            "paging": true,
            "lengthChange": true,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
        }
        });
    </script>
}
              